Fix setting properties with group assignment
sabre-io/vobject pull request #523
Opened 2020-11-14 09:06 UTC by mstilkerich

Setting properties that are part of a group is broken since version 4.0.0. The `Component::remove()` method for the specific case of a property given by its name (as string) that includes a group prefix will throw an exception. However, I believe the exception is only intended for the usage of this function where the property to remove is given as an object reference, not as a string, where the given property/component is not a child of component the remove() method is called on.

Example code to trigger the exception:
```php
<?php

use Sabre\VObject;
use Sabre\VObject\Component\VCard;
include_once dirname(__FILE__) . "/vendor/autoload.php";

$vcard = new VObject\Component\VCard([
        'VERSION' => '3.0',
        'item2.X-ABLabel' => "Foo", // triggers exception
]);

$vcard->{"item1.X-ABLabel"} = "SpecialLabel"; // also triggers exception

print $vcard->serialize();
```

The exception will be triggered for both the usage in the constructor as well as by a separate set operation.

2020-11-17 07:58 UTC, DeepDiver1975 requested changes
Thanks a lot for your contribution!

Can I ask you to add a unit test for this case? :+1:

2020-11-17 10:54 UTC, phil-davis reviewed
Code looks reasonable. Just needs unit test(s) so this does not get broken again in future.

2020-11-17 12:26 UTC, mstilkerich commented
Hello, I added a test case.

2021-01-15 15:25 UTC, mstilkerich commented
Hello, I added the requested test. Is there still a problem?

2021-02-12 00:44 UTC, phil-davis commented
With the new test case on `master`
```
There was 1 error:

1) Sabre\VObject\ComponentTest::testAddGroupProperties
InvalidArgumentException: The item you passed to remove() was not a child of this component

/home/phil/git/sabre-io/vobject/lib/Component.php:165
/home/phil/git/sabre-io/vobject/lib/Component.php:483
/home/phil/git/sabre-io/vobject/tests/VObject/ComponentTest.php:82

ERRORS!
Tests: 1721, Assertions: 2639, Errors: 1.
Script phpunit --configuration tests/phpunit.xml handling the phpunit event returned with error code 2

```

That's good, the test fails. And passes with the fix.

2021-02-12 00:46 UTC, phil-davis approved these changes

2021-02-12 05:17 UTC, merged